# Generated by Django 3.2.2 on 2021-05-14 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Номер сертификата')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на сертификат')),
                ('nominal', models.IntegerField(default=1, verbose_name='Номинал')),
                ('published_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('certificate_image', models.ImageField(default=None, upload_to='')),
                ('status', models.CharField(choices=[('RECEIVED', 'Получен'), ('NOSENT', 'Неотправлен'), ('PAID', 'Оплачен'), ('SENT', 'Отправлен')], default='NOSENT', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MyCertsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='balance')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_by_user', to='main.mycertsuser'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
