# Generated by Django 3.2.2 on 2021-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycertsuser',
            name='profile_photo',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
