# Generated by Django 3.2.2 on 2021-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mycertsuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertsuser',
            name='profile_photo',
            field=models.ImageField(default='C:\\Projects\\commerce\\MoCertsWthhoutWix\\static\\img\\profile.jpg', upload_to=''),
        ),
    ]
