# Generated by Django 3.2.2 on 2021-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mycertsuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertsuser',
            name='profile_photo',
            field=models.ImageField(default='/static/img/profile.jpg', upload_to=''),
        ),
    ]
