# Generated by Django 3.2.2 on 2021-05-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mycertsuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertsuser',
            name='profile_photo',
            field=models.ImageField(default='C:\\Projects\\commerce\\MoCertsWthhoutWix\\media\\profile.jpg', upload_to=''),
        ),
    ]
