# Generated by Django 3.2.2 on 2021-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_mycertsuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycertsuser',
            name='profile_photo',
            field=models.ImageField(default='profile.jpg', upload_to=''),
        ),
    ]
